package com.edunest.backend.modules.syllabus.service.impl;
import com.edunest.backend.common.exception.*; import com.edunest.backend.common.util.PublicIdUtils; import com.edunest.backend.modules.branch.entity.Branch; import com.edunest.backend.modules.branch.repository.BranchRepository; import com.edunest.backend.modules.semester.entity.Semester; import com.edunest.backend.modules.semester.repository.SemesterRepository; import com.edunest.backend.modules.subject.dto.SubjectResponseDto; import com.edunest.backend.modules.subject.entity.Subject; import com.edunest.backend.modules.subject.repository.SubjectRepository; import com.edunest.backend.modules.syllabus.dto.*; import com.edunest.backend.modules.syllabus.service.SyllabusAdminService; import com.edunest.backend.modules.topic.dto.TopicResponse; import com.edunest.backend.modules.topic.entity.Topic; import com.edunest.backend.modules.topic.repository.TopicRepository; import com.edunest.backend.modules.unit.dto.UnitResponse; import com.edunest.backend.modules.unit.entity.Unit; import com.edunest.backend.modules.unit.repository.UnitRepository; import com.edunest.backend.modules.year.entity.AcademicYear; import com.edunest.backend.modules.year.repository.AcademicYearRepository; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service @RequiredArgsConstructor public class SyllabusAdminServiceImpl implements SyllabusAdminService {
private final SubjectRepository subjects; private final UnitRepository units; private final TopicRepository topics; private final BranchRepository branches; private final SemesterRepository semesters; private final AcademicYearRepository years;
@Override @Transactional public SubjectResponseDto createSubject(SubjectRequest r){if(subjects.findByCode(r.getCode().trim()).isPresent())throw new BadRequestException("Subject code already exists");Subject s=new Subject();apply(s,r);s.setActive(true);return mapSubject(subjects.save(s));}
@Override @Transactional public SubjectResponseDto updateSubject(String id,SubjectRequest r){Long sid=PublicIdUtils.parseSubjectId(id);Subject s=subjects.findById(sid).orElseThrow(()->new ResourceNotFoundException("Subject not found"));subjects.findByCode(r.getCode().trim()).filter(x->!x.getId().equals(sid)).ifPresent(x->{throw new BadRequestException("Subject code already exists");});apply(s,r);return mapSubject(subjects.save(s));}
@Override @Transactional public SubjectResponseDto deactivateSubject(String id){Subject s=subjects.findById(PublicIdUtils.parseSubjectId(id)).orElseThrow(()->new ResourceNotFoundException("Subject not found"));s.setActive(false);return mapSubject(s);}
@Override @Transactional public UnitResponse createUnit(UnitRequest r){Subject s=activeSubject(r.getSubjectId());if(units.existsBySubjectIdAndUnitNumber(s.getId(),r.getUnitNumber()))throw new BadRequestException("Unit number already exists for this subject");return mapUnit(units.save(Unit.builder().subject(s).unitNumber(r.getUnitNumber()).chapterName(r.getChapterName().trim()).description(norm(r.getDescription())).active(true).build()));}
@Override @Transactional public UnitResponse updateUnit(String id,UnitRequest r){Unit u=units.findById(PublicIdUtils.parseUnitId(id)).orElseThrow(()->new ResourceNotFoundException("Unit not found"));Subject s=activeSubject(r.getSubjectId());if(units.existsBySubjectIdAndUnitNumberAndIdNot(s.getId(),r.getUnitNumber(),u.getId()))throw new BadRequestException("Unit number already exists for this subject");u.setSubject(s);u.setUnitNumber(r.getUnitNumber());u.setChapterName(r.getChapterName().trim());u.setDescription(norm(r.getDescription()));return mapUnit(units.save(u));}
@Override @Transactional public UnitResponse deactivateUnit(String id){Unit u=units.findById(PublicIdUtils.parseUnitId(id)).orElseThrow(()->new ResourceNotFoundException("Unit not found"));u.setActive(false);return mapUnit(u);}
@Override @Transactional public TopicResponse createTopic(TopicRequest r){Unit u=activeUnit(r.getUnitId());if(topics.existsByUnitIdAndTopicNumber(u.getId(),r.getTopicNumber()))throw new BadRequestException("Topic number already exists for this unit");return mapTopic(topics.save(Topic.builder().unit(u).topicNumber(r.getTopicNumber()).name(r.getName().trim()).description(norm(r.getDescription())).active(true).build()));}
@Override @Transactional public TopicResponse updateTopic(String id,TopicRequest r){Topic t=topics.findById(PublicIdUtils.parseTopicId(id)).orElseThrow(()->new ResourceNotFoundException("Topic not found"));Unit u=activeUnit(r.getUnitId());if(topics.existsByUnitIdAndTopicNumberAndIdNot(u.getId(),r.getTopicNumber(),t.getId()))throw new BadRequestException("Topic number already exists for this unit");t.setUnit(u);t.setTopicNumber(r.getTopicNumber());t.setName(r.getName().trim());t.setDescription(norm(r.getDescription()));return mapTopic(topics.save(t));}
@Override @Transactional public TopicResponse deactivateTopic(String id){Topic t=topics.findById(PublicIdUtils.parseTopicId(id)).orElseThrow(()->new ResourceNotFoundException("Topic not found"));t.setActive(false);return mapTopic(t);}
private void apply(Subject s,SubjectRequest r){Branch b=branches.findByIdAndActiveTrue(PublicIdUtils.parseBranchId(r.getBranchId())).orElseThrow(()->new ResourceNotFoundException("Branch not found"));Semester sem=semesters.findByIdAndActiveTrue(PublicIdUtils.parseSemesterId(r.getSemesterId())).orElseThrow(()->new ResourceNotFoundException("Semester not found"));AcademicYear y=years.findByIdAndActiveTrue(PublicIdUtils.parseAcademicYearId(r.getAcademicYearId())).orElseThrow(()->new ResourceNotFoundException("Academic year not found"));if(!b.getAcademicYear().getId().equals(y.getId())||!sem.getAcademicYear().getId().equals(y.getId()))throw new BadRequestException("Branch, semester and academic year must match");s.setName(r.getName().trim());s.setCode(r.getCode().trim());s.setSubjectCategory(r.getSubjectCategory());s.setExamType(r.getExamType());s.setLectureHours(r.getLectureHours());s.setTutorialHours(r.getTutorialHours());s.setPracticalHours(r.getPracticalHours());s.setInSemMarks(r.getInSemMarks());s.setEndSemMarks(r.getEndSemMarks());s.setPracticalMarks(r.getPracticalMarks());s.setOralMarks(r.getOralMarks());s.setTermWorkMarks(r.getTermWorkMarks());s.setCredits(r.getCredits());s.setElective(r.isElective());s.setElectiveGroup(norm(r.getElectiveGroup()));s.setHonors(r.isHonors());s.setMinor(r.isMinor());s.setBranch(b);s.setSemester(sem);s.setAcademicYear(y);}
private Subject activeSubject(String id){return subjects.findById(PublicIdUtils.parseSubjectId(id)).filter(Subject::isActive).orElseThrow(()->new ResourceNotFoundException("Subject not found"));} private Unit activeUnit(String id){return units.findByIdAndActiveTrue(PublicIdUtils.parseUnitId(id)).orElseThrow(()->new ResourceNotFoundException("Unit not found"));} private String norm(String v){if(v==null)return null;String x=v.trim();return x.isEmpty()?null:x;}
private SubjectResponseDto mapSubject(Subject s){return SubjectResponseDto.builder().id(PublicIdUtils.subjectId(s.getId())).name(s.getName()).code(s.getCode()).active(s.isActive()).subjectCategory(s.getSubjectCategory()).examType(s.getExamType()).lectureHours(s.getLectureHours()).tutorialHours(s.getTutorialHours()).practicalHours(s.getPracticalHours()).inSemMarks(s.getInSemMarks()).endSemMarks(s.getEndSemMarks()).practicalMarks(s.getPracticalMarks()).oralMarks(s.getOralMarks()).termWorkMarks(s.getTermWorkMarks()).credits(s.getCredits()).elective(s.isElective()).electiveGroup(s.getElectiveGroup()).honors(s.isHonors()).minor(s.isMinor()).branchId(PublicIdUtils.branchId(s.getBranch().getId())).branchName(s.getBranch().getName()).semesterId(PublicIdUtils.semesterId(s.getSemester().getId())).semesterName(s.getSemester().getName()).academicYearId(PublicIdUtils.academicYearId(s.getAcademicYear().getId())).academicYearName(s.getAcademicYear().getName()).build();}
private UnitResponse mapUnit(Unit u){return UnitResponse.builder().id(PublicIdUtils.unitId(u.getId())).unitNumber(u.getUnitNumber()).chapterName(u.getChapterName()).description(u.getDescription()).active(u.isActive()).subjectId(PublicIdUtils.subjectId(u.getSubject().getId())).subjectName(u.getSubject().getName()).subjectCode(u.getSubject().getCode()).build();}
private TopicResponse mapTopic(Topic t){return TopicResponse.builder().id(PublicIdUtils.topicId(t.getId())).topicNumber(t.getTopicNumber()).name(t.getName()).description(t.getDescription()).active(t.isActive()).unitId(PublicIdUtils.unitId(t.getUnit().getId())).unitNumber(t.getUnit().getUnitNumber()).subjectId(PublicIdUtils.subjectId(t.getUnit().getSubject().getId())).subjectName(t.getUnit().getSubject().getName()).build();}
}