package com.edunest.backend.modules.syllabus.controller; import com.edunest.backend.common.response.ApiResponse; import com.edunest.backend.modules.subject.dto.SubjectResponseDto; import com.edunest.backend.modules.syllabus.dto.*; import com.edunest.backend.modules.syllabus.service.SyllabusAdminService; import com.edunest.backend.modules.topic.dto.TopicResponse; import com.edunest.backend.modules.unit.dto.UnitResponse; import jakarta.validation.Valid; import lombok.RequiredArgsConstructor; import org.springframework.http.ResponseEntity; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/admin/syllabus") @RequiredArgsConstructor @PreAuthorize("hasRole('ADMIN')") public class AdminSyllabusController { private final SyllabusAdminService s;
@PostMapping("/subjects") public ResponseEntity<ApiResponse<SubjectResponseDto>> cs(@Valid @RequestBody SubjectRequest r){return ok("Subject created successfully",s.createSubject(r));}
@PutMapping("/subjects/{id}") public ResponseEntity<ApiResponse<SubjectResponseDto>> us(@PathVariable String id,@Valid @RequestBody SubjectRequest r){return ok("Subject updated successfully",s.updateSubject(id,r));}
@DeleteMapping("/subjects/{id}") public ResponseEntity<ApiResponse<SubjectResponseDto>> ds(@PathVariable String id){return ok("Subject deactivated successfully",s.deactivateSubject(id));}
@PostMapping("/units") public ResponseEntity<ApiResponse<UnitResponse>> cu(@Valid @RequestBody UnitRequest r){return ok("Unit created successfully",s.createUnit(r));}
@PutMapping("/units/{id}") public ResponseEntity<ApiResponse<UnitResponse>> uu(@PathVariable String id,@Valid @RequestBody UnitRequest r){return ok("Unit updated successfully",s.updateUnit(id,r));}
@DeleteMapping("/units/{id}") public ResponseEntity<ApiResponse<UnitResponse>> du(@PathVariable String id){return ok("Unit deactivated successfully",s.deactivateUnit(id));}
@PostMapping("/topics") public ResponseEntity<ApiResponse<TopicResponse>> ct(@Valid @RequestBody TopicRequest r){return ok("Topic created successfully",s.createTopic(r));}
@PutMapping("/topics/{id}") public ResponseEntity<ApiResponse<TopicResponse>> ut(@PathVariable String id,@Valid @RequestBody TopicRequest r){return ok("Topic updated successfully",s.updateTopic(id,r));}
@DeleteMapping("/topics/{id}") public ResponseEntity<ApiResponse<TopicResponse>> dt(@PathVariable String id){return ok("Topic deactivated successfully",s.deactivateTopic(id));}
private <T> ResponseEntity<ApiResponse<T>> ok(String m,T d){return ResponseEntity.ok(ApiResponse.<T>builder().success(true).message(m).data(d).build());}}
